### ISSUE TITLE
My god it keeps crashing (Shaders problem with TACZ NPCs)

### ISSUE THREAD

**Issue by Fostrof08c** [Corrinedev/tacz-npcs#1]
_Crash.log below_

Okay first of all sorry for saying it was correct I literally didnt check
But the bug still persists even with using latest update
When you use any shaders where NPCs are on screen, game instantly crashes
Mods I use (that I consider are responsible for this crash) are as follows:
- [GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib) (latest update)
- [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus)
- [Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium)

Other optimization mods I use: 
- [Architectury API](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
- [Starlight](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
- [Tactical Movement Renewed](https://www.curseforge.com/minecraft/mc-mods/expressive-advanced)
- [Chunky](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator-forge)
- [FerriteCore](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
- [Player Animator](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
- [Packet Fixer](https://www.curseforge.com/minecraft/mc-mods/packet-fixer)
- [CameraOverhaul (Forge)](https://www.curseforge.com/minecraft/mc-mods/camera-overhaul-forge)

[latest.log](https://github.com/user-attachments/files/18218796/latest.log)
[latest on odt](https://github.com/user-attachments/files/18218830/crashlog.on.odf.odt)

**Comment by Corrinedev** [comment]
if you have entity texture/model features mod try removing that

**Comment by Fostrof08c** [comment]
Ok so, tried literally everything and it seems to keep crashing. At this point it may bea vram issue or something as I even tried a barebone instance (TACZ + Embeddium and Oculus +  NPCs + SmartBrain + Geckolib (+ geckolib fix aswell)) and kept crashing; tried downgrading embeddium and oculus aswell as Geckolib and nothing. I might keep trying to find a compatible version but seems unlikely

**Comment by Corrinedev** [comment]
fixed in 1.1.1!!
