### ISSUE TITLE
Game breaks AGAIN with Oculus' new update 1.8.0 (Shaders problem)

### ISSUE THREAD

**Issue by Fostrof08c** [Corrinedev/tacz-npcs#2]
NOTE: THE GAME STILL RUNS FINE WITH THE PREVIOUS OCULUS UPDATE 1.7.0
Stupid devs decided to ruin it all over Bethesda-style with a new update breaking your fix to the Shaders+NPCs issue AGAIN
Here's the crash.log:

[latest.log](https://github.com/user-attachments/files/18245895/latest.log)

[crash-2024-12-25_13.23.00-client.txt](https://github.com/user-attachments/files/18245897/crash-2024-12-25_13.23.00-client.txt)

**Comment by Corrinedev** [comment]
gosh darn dangit

**Comment by Corrinedev** [comment]
yea this looks like an oculus issue if the update broke it, not much i can do, just run with 1.7.0 for now
